In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as pp

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a.dtype

dtype('int64')

In [8]:
a = np.array([1,2,3,4,5], dtype=np.float64)

In [9]:
a

array([1., 2., 3., 4., 5.])

In [13]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [15]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], 'd') #'d' shorthand for double, ie float64
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [16]:
a.ndim, a.shape, a.size

(2, (2, 5), 10)

In [17]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.linspace(0,10,4) #3rd arguement is the number of elements equally spaced

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [21]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.random.standard_normal([2,4])

array([[ 0.84492856, -0.08768315, -0.69342372,  0.03671631],
       [-0.3003856 ,  0.49797795, -0.63267104,  0.79850661]])

In [23]:
a = np.random.standard_normal([2,3])
b = np.random.standard_normal([2,3])

In [24]:
np.vstack([a,b])

array([[ 1.5796926 ,  1.03632026,  0.13400811],
       [-0.85169287,  1.58623838,  0.35343711],
       [-1.55617721, -0.06864433, -0.24931937],
       [ 0.08602319,  1.16218821, -0.74515523]])

In [27]:
np.hstack([a,b])

array([[ 1.5796926 ,  1.03632026,  0.13400811, -1.55617721, -0.06864433,
        -0.24931937],
       [-0.85169287,  1.58623838,  0.35343711,  0.08602319,  1.16218821,
        -0.74515523]])

In [26]:
a.transpose()

array([[ 1.5796926 , -0.85169287],
       [ 1.03632026,  1.58623838],
       [ 0.13400811,  0.35343711]])

In [31]:
np.save('example.npy', b)

In [32]:
b1 = np.load('example.npy')

In [33]:
b1

array([[-1.55617721, -0.06864433, -0.24931937],
       [ 0.08602319,  1.16218821, -0.74515523]])