In [41]:
import numpy as np

In [42]:
v = np.linspace(0,10, 5)

In [43]:
v[2:]

array([  5. ,   7.5,  10. ])

In [44]:
vv = np.random.random([3,4])

In [45]:
vv

array([[ 0.87651622,  0.73815743,  0.48131324,  0.43360231],
       [ 0.41640827,  0.4322873 ,  0.20504227,  0.57879415],
       [ 0.3207334 ,  0.56208388,  0.44855692,  0.43699168]])

In [46]:
vv[0,0]

0.87651622034546228

In [47]:
vv[2,3]

0.43699167913585246

In [48]:
ll = [[1,2,3],[4,5,6],[7,8,9]]
ll

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [49]:
ll[0,2] #can't use convenient double indexing to access element in list of lists

TypeError: list indices must be integers or slices, not tuple

In [50]:
ll[0][2] #numpy provides extension of indexing by using repeat bracket

3

In [51]:
v

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [52]:
vv

array([[ 0.87651622,  0.73815743,  0.48131324,  0.43360231],
       [ 0.41640827,  0.4322873 ,  0.20504227,  0.57879415],
       [ 0.3207334 ,  0.56208388,  0.44855692,  0.43699168]])

In [53]:
v[0:2]

array([ 0. ,  2.5])

In [54]:
vv[0:3, 1]

array([ 0.73815743,  0.4322873 ,  0.56208388])

In [55]:
vv[0:2, 1:3]

array([[ 0.73815743,  0.48131324],
       [ 0.4322873 ,  0.20504227]])

In [56]:
vv[:, ::2] #slice all rows and all columns in steps of 2

array([[ 0.87651622,  0.48131324],
       [ 0.41640827,  0.20504227],
       [ 0.3207334 ,  0.44855692]])

In [57]:
v2 = v[2:4]
v2

array([ 5. ,  7.5])

In [58]:
v2[0] = 0 #will change the original array v as well

In [59]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [60]:
v3 = v[2:4].copy() #will not change the original array

In [61]:
v3[0] = 1.5

In [62]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [63]:
v[[1,3]] #advanced extension of slicing in numpy to use list of indices

array([ 2.5,  7.5])

In [64]:
v > 0

array([False,  True, False,  True,  True], dtype=bool)

In [65]:
bool_index = v>0

In [66]:
v[bool_index]

array([  2.5,   7.5,  10. ])

In [67]:
vv

array([[ 0.87651622,  0.73815743,  0.48131324,  0.43360231],
       [ 0.41640827,  0.4322873 ,  0.20504227,  0.57879415],
       [ 0.3207334 ,  0.56208388,  0.44855692,  0.43699168]])

In [68]:
vv > 0.5

array([[ True,  True, False, False],
       [False, False, False,  True],
       [False,  True, False, False]], dtype=bool)

In [69]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [70]:
vv

array([[ 1.75303244,  1.47631486,  0.48131324,  0.43360231],
       [ 0.41640827,  0.4322873 ,  0.20504227,  1.1575883 ],
       [ 0.3207334 ,  1.12416776,  0.44855692,  0.43699168]])