In [2]:
import numpy as np

 Numpy container can also contain rows of mixed types. Rows created using numpy tuple and headers as dict

In [9]:
reca = np.array([(1, (2.0, 3.5), 'hey'), (2, (4.0, 5.0), 'n')],
                 dtype=[('x', np.int32), ('y', np.float64,2), ('z', np.str, 4)])

In [10]:
reca

array([(1, [2. , 3.5], 'hey'), (2, [4. , 5. ], 'n')],
      dtype=[('x', '<i4'), ('y', '<f8', (2,)), ('z', '<U4')])

In [11]:
reca[0]

(1, [2. , 3.5], 'hey')

In [12]:
reca['y']

array([[2. , 3.5],
       [4. , 5. ]])

In [14]:
reca['y'][0]

array([2. , 3.5])

In [17]:
reca[0]['y']

array([2. , 3.5])

In [18]:
reca[0]['y'][0]6

2.0

In [19]:
np.datetime64('2018') #datetime64 to distinguish from python built-in timedate

numpy.datetime64('2018')

In [22]:
np.datetime64('2018-07-04')

numpy.datetime64('2018-07-04')

In [23]:
np.datetime64('2018-07-04') - np.datetime64('2018-05-30')

numpy.timedelta64(35,'D')

In [26]:
np.datetime64('2018-07-04') + np.timedelta64(12, 'D')

numpy.datetime64('2018-07-16')

In [27]:
np.datetime64('2018-07-04').astype(float)

17716.0

In [30]:
r = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-03-01'))

In [31]:
r

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23', '2018-02-24',
       '2018-02-25', '2018-02-26', '2018-02-27', '2018-02-28'],
      dtype='datetime64[D]')